name: agile_front
version: 0.1.0
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.4
  yaml: ^3.1.2
  json_annotation: ^4.8.1
  flutter_localization: ^0.3.1
  go_router: ^14.8.1
  http: ^1.3.0
  intl_phone_field: ^3.2.0
  intl: any
  provider: ^6.1.2
  dart_gql:
    git:
      url: https://github.com/pjmd89/dart_gql
      ref: main
  graphql: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
